Assignment-1 
Based on NumPy 

Q1: Questions on Basic NumPy Array 

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
# print(arr[::-1])
np.flip(arr)

array([5, 4, 6, 3, 2, 1])

In [2]:
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

array2 = array1.reshape((1, 9))
print("Reshaped array:", array2)

array3 = array1.flatten()
print("Flattened with flatten():", array3)

array4 = array1.ravel()
print("Flattened with ravel():", array4)


Reshaped array: [[1 2 3 2 4 5 1 2 3]]
Flattened with flatten(): [1 2 3 2 4 5 1 2 3]
Flattened with ravel(): [1 2 3 2 4 5 1 2 3]


In [3]:
arr1 = np.array([[1, 2], [3, 4]]) 
arr2 = np.array([[1, 2], [3, 4]]) 
# np.array_equal(arr1, arr2)
np.allclose(arr1, arr2)

True

In [4]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1]) 
print(np.bincount(x).argmax())

1


In [5]:
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
max_y=np.bincount(y)
maximum=max(max_y)

for i in range (len(max_y)):
    if max_y[i]==maximum:
        print (i, end = " ")

1 3 

In [6]:
z=np.array([-1, -1, 2, 3, -1, 2, 3, 3])
values,counts=np.unique(z,return_counts=True)
maximum=max(counts)
for i in range (len(values)):
    if(maximum==counts[i]):
        print(values[i],end=" ")

-1 3 

In [7]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print(f"The sum of all elements is:{np.sum(gfg)}")
print("\nSum of each row:")
print(np.sum(gfg,axis=1))
print(f"\nSum of each column :{np.sum(gfg,axis=0)}")

The sum of all elements is:45

Sum of each row:
[[14]
 [16]
 [15]]

Sum of each column :[[20  9 16]]


In [8]:
n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag= np.diagonal(n_array)
print(f"\n i.Diagonal elements :{diag}")
print(f"\n Sum of diagonal elements :{sum(diag)}")
print(f"\n Sum of diagonal elements :{np.trace(n_array)}")
print(f"\n ii., iii. Eigenvalues, Eigenvectors of a matrix :")
print(f"\n{np.linalg.eig(n_array)}")
print(f"\n iv. Inverse of a matrix :{np.linalg.inv(n_array)}")
print(f"\n v. Determinant of a matrix :{np.linalg.det(n_array)}")


 i.Diagonal elements :[55 44 77]

 Sum of diagonal elements :176

 Sum of diagonal elements :176

 ii., iii. Eigenvalues, Eigenvectors of a matrix :

EigResult(eigenvalues=array([28.097044  , 49.73460452, 98.16835147]), eigenvectors=array([[-0.34637121,  0.15017693,  0.4574917 ],
       [ 0.72784061,  0.4852124 ,  0.28447814],
       [-0.59184038, -0.8614034 ,  0.84248058]]))

 iv. Inverse of a matrix :[[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]

 v. Determinant of a matrix :137180.0000000001


In [9]:
# (i.)
import numpy as np
p = [[1, 2], [2, 3]] 
q = [[4, 5], [6, 7]] 
multiplication= np.matmul(p,q)
print(f" The product of matrix p and q is {multiplication}")
# We cannot have one covariance for 2 different matrices, so we combine them first 
combine=np.vstack((p,q))
covar=np.cov(combine.T)#transpose we have taken to get variables in a row.
print(f" The covariance of combined matrix p and q is {covar}")

 The product of matrix p and q is [[16 19]
 [26 31]]
 The covariance of combined matrix p and q is [[4.91666667 4.91666667]
 [4.91666667 4.91666667]]


In [10]:
# (ii.)
p1 = np.array([[1, 2], [2, 3], [4, 5]]) 
q1 = np.array([[4, 5, 1], [6, 7, 2]])
multip=np.matmul(p1,q1) #This is not element-wise multiplication, it's dot product-based matrix multiplication.
# formula used by matmul: multip[i][j] = sum(p1[i][k] * q1[k][j] for k in range(n))
print(f" The product of matrix p1 and q1 is {multip}")
combined=np.hstack((p1, q1.T))
covariance=np.cov(combined.T)
print(f" The covariance of combined matrix p1 and q1 is {covariance}")

 The product of matrix p1 and q1 is [[16 19  5]
 [26 31  8]
 [46 55 14]]
 The covariance of combined matrix p1 and q1 is [[ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [ 2.33333333  2.33333333 -2.66666667 -3.5       ]
 [-2.66666667 -2.66666667  4.33333333  5.5       ]
 [-3.5        -3.5         5.5         7.        ]]


In [11]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
#dot product: inner product
# Method 1 for inner multiplication
y_t=y.T
mul1= x @ y_t
# Method 1 for inner multiplication
mul2=np.matmul(x,y_t)
print(f"The result for inner product from method 1 and method 2 is {mul1},{mul2} respectively")
# Outer multiplication means a matrix is produced by multiplying each element of x by all elements of y.
outMul=np.outer(x,y)
print(f"The result for outer product is {outMul}")
#Cartesian product creates all combinations of rows from matrix A and matrix B.
from itertools import product
cartesian_product = [np.hstack((a, b)) for a, b in product(x, y)]
result = np.array(cartesian_product)
print(f"The result for cartesian product is {result}")

The result for inner product from method 1 and method 2 is [[17 52]
 [13 62]],[[17 52]
 [13 62]] respectively
The result for outer product is [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
The result for cartesian product is [[ 2  3  4  1  5  0]
 [ 2  3  4  5 10  3]
 [ 3  2  9  1  5  0]
 [ 3  2  9  5 10  3]]


Q2: Based on NumPy Mathematics and Statistics

In [12]:
import numpy as np
print("i.")
array = np.array([[1, -2, 3],[-4, 5, -6]])
Absolute=np.abs(array)
print(f"The element-wise absolute value of array is: {Absolute}")

print("\n ii.")
print("(a). for flattened array")
flat=array.flatten()
p25_flat = np.percentile(flat, 25)
p50_flat = np.percentile(flat, 50)  # same as median
p75_flat = np.percentile(flat, 75)
print(f"Flattened array percentiles (25, 50, 75): {p25_flat}, {p50_flat}, and {p75_flat}")

print("\n (b). for columns")
p_col = np.percentile(array, [25, 50, 75], axis=0)
print(f"Percentiles (columns):{p_col}")

print("\n (c). for rows")
p_row = np.percentile(array, [25, 50, 75], axis=1)
print(f"Percentiles (columns):{p_row}")

print("\n iii.")
print("(a). for flattened array")
print(f"\n The Mean, Median, and Standard Deviation of flattened array: {np.mean(flat)}, {np.median(flat)},and {np.std(flat)}")

print("\n (b). for columns")
print(f"\n The Mean, Median, and Standard Deviation of columns: {np.mean(array,axis=0)}, {np.median(array,axis=0)},and {np.std(array,axis=0)}")

print("\n (c). for rows")
print(f"\n The Mean, Median, and Standard Deviation of rows: {np.mean(array,axis=1)}, {np.median(array,axis=1)},and {np.std(array,axis=1)}")


i.
The element-wise absolute value of array is: [[1 2 3]
 [4 5 6]]

 ii.
(a). for flattened array
Flattened array percentiles (25, 50, 75): -3.5, -0.5, and 2.5

 (b). for columns
Percentiles (columns):[[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]

 (c). for rows
Percentiles (columns):[[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

 iii.
(a). for flattened array

 The Mean, Median, and Standard Deviation of flattened array: -0.5, -0.5,and 3.8622100754188224

 (b). for columns

 The Mean, Median, and Standard Deviation of columns: [-1.5  1.5 -1.5], [-1.5  1.5 -1.5],and [2.5 3.5 4.5]

 (c). for rows

 The Mean, Median, and Standard Deviation of rows: [ 0.66666667 -1.66666667], [ 1. -4.],and [2.05480467 4.78423336]


Q3: Based on Searching and Sorting 

In [13]:
print("(a)")
print("i.",end=" ")
array = np.array([10, 52, 62, 16, 16, 54, 453])
sorted=np.sort(array)
print(f"The sorted array is: {sorted}")
print("\nii.",end=" ")
print(f"The indices of sorted array are: {np.argsort(array)}")

print("\niii.",end=" ")
print(f"The 4 smallest elements are: {sorted[0:4]}")

# print("\niv.",end=" ")
# print(f"The 5 largest elemets are: {sorted[-6:-1]}")
#with upper last wala element is not coming, why?
# Correct Way:
#print(f"The 5 largest elemets are: {sorted[-5:]}")
print("\niv.",end=" ")
print(f"The 5 largest elemets are: {sorted[-5:][::-1]}")

(a)
i. The sorted array is: [ 10  16  16  52  54  62 453]

ii. The indices of sorted array are: [0 3 4 1 5 2 6]

iii. The 4 smallest elements are: [10 16 16 52]

iv. The 5 largest elemets are: [453  62  54  52  16]


In [14]:
print("(b)")
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
#method 1
print ("i.",end=" ")
integer= array[array == array.astype(int)]
print(f"The interger elements are: {integer}")

integer_elements = array[np.equal(np.mod(array, 1), 0)]
print("i. Integer elements only:", integer_elements)

# print ("ii.",end=" ")                       _
# floa= array[array == array.astype(float)]    |- Wrong
# print(f"The interger elements are: {floa}") _

float_elements = array[np.mod(array, 1) != 0]
print("ii. Float elements only:", float_elements)

(b)
i. The interger elements are: [1. 2. 3. 2.]
i. Integer elements only: [1. 2. 3. 2.]
ii. Float elements only: [1.2 2.2]


In [ ]:
(b) Load the saved file into jupyter notebook?

# tried a lot not able to solve these two, will try again after asking doubt 